# tabs/catalog_queries.py
from .common_xmla import build_xmla_query

# Central registry of SQL fragments and their expected columns.
CATALOG_QUERIES = {
    "columns_df": {
        "sql": """
            SELECT [CATALOG_NAME], [DATASET_NAME], [COLUMN_NAME], [DATA_TYPE], [EXPRESSION], [CONNECTION_ID]
            FROM $system.DBSCHEMA_COLUMNS
        """,
        "columns": [
            "CATALOG_NAME", "DATASET_NAME", "COLUMN_NAME", "DATA_TYPE", "EXPRESSION", "CONNECTION_ID"
        ],
    },
    "tables_df": {
        "sql": """
            SELECT [CATALOG_NAME], [CUBE_GUID], [DATASET_NAME], [DATABASE], [TABLE], [SCHEMA], [EXPRESSION], [CONNECTION_ID]
            FROM $system.DBSCHEMA_TABLES
        """,
        "columns": [
            "CATALOG_NAME", "CUBE_GUID", "DATASET_NAME", "DATABASE", "TABLE", "SCHEMA", "EXPRESSION", "CONNECTION_ID"
        ],
    },
    "dimensions_detail_df": {
        "sql": """
            SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_NAME], [DIMENSION_GUID],
                   [DIMENSION_UNIQUE_NAME], [DIMENSION_CAPTION], [DIMENSION_ORDINAL], [DIMENSION_TYPE],
                   [DIMENSION_CARDINALITY], [DEFAULT_HIERARCHY], [DESCRIPTION], [IS_VIRTUAL], [IS_READWRITE],
                   [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_NAME], [DIMENSION_IS_VISIBLE]
            FROM $system.MDSCHEMA_DIMENSIONS
            WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt;'[Measures]'
        """,
        "columns": [
            "CATALOG_NAME", "SCHEMA_NAME", "CUBE_NAME", "CUBE_GUID", "DIMENSION_NAME", "DIMENSION_GUID",
            "DIMENSION_UNIQUE_NAME", "DIMENSION_CAPTION", "DIMENSION_ORDINAL", "DIMENSION_TYPE",
            "DIMENSION_CARDINALITY", "DEFAULT_HIERARCHY", "DESCRIPTION", "IS_VIRTUAL", "IS_READWRITE",
            "DIMENSION_UNIQUE_SETTINGS", "DIMENSION_MASTER_NAME", "DIMENSION_IS_VISIBLE"
        ],
    },
    "hierarchies_detail_df": {
        "sql": """
            SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME],
                   [HIERARCHY_NAME], [HIERARCHY_UNIQUE_NAME], [HIERARCHY_GUID], [HIERARCHY_CAPTION],
                   [DIMENSION_TYPE], [HIERARCHY_CARDINALITY], [DEFAULT_MEMBER], [ALL_MEMBER], [DESCRIPTION],
                   [STRUCTURE], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS],
                   [DIMENSION_MASTER_UNIQUE_NAME], [DIMENSION_IS_VISIBLE], [HIERARCHY_ORIGIN],
                   [HIERARCHY_DISPLAY_FOLDER], [INSTANCE_SELECTION], [GROUPING_BEHAVIOR], [STRUCTURE_TYPE],
                   [DIMENSION_IS_SHARED], [HIERARCHY_IS_VISIBLE], [HIERARCHY_ORDINAL]
            FROM $system.MDSCHEMA_HIERARCHIES
            WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'
        """,
        "columns": [
            "CATALOG_NAME", "SCHEMA_NAME", "CUBE_NAME", "CUBE_GUID", "DIMENSION_UNIQUE_NAME",
            "HIERARCHY_NAME", "HIERARCHY_UNIQUE_NAME", "HIERARCHY_GUID", "HIERARCHY_CAPTION",
            "DIMENSION_TYPE", "HIERARCHY_CARDINALITY", "DEFAULT_MEMBER", "ALL_MEMBER", "DESCRIPTION",
            "STRUCTURE", "IS_VIRTUAL", "IS_READWRITE", "DIMENSION_UNIQUE_SETTINGS",
            "DIMENSION_MASTER_UNIQUE_NAME", "DIMENSION_IS_VISIBLE", "HIERARCHY_ORIGIN",
            "HIERARCHY_DISPLAY_FOLDER", "INSTANCE_SELECTION", "GROUPING_BEHAVIOR", "STRUCTURE_TYPE",
            "DIMENSION_IS_SHARED", "HIERARCHY_IS_VISIBLE", "HIERARCHY_ORDINAL"
        ],
    },
    "levels_detail_df": {
        "sql": """
            SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME],
                   [HIERARCHY_UNIQUE_NAME], [LEVEL_NAME], [LEVEL_UNIQUE_NAME], [LEVEL_GUID], [LEVEL_CAPTION],
                   [LEVEL_NUMBER], [LEVEL_CARDINALITY], [LEVEL_TYPE], [DESCRIPTION], [CUSTOM_ROLLUP_SETTINGS],
                   [LEVEL_UNIQUE_SETTINGS], [LEVEL_IS_VISIBLE], [LEVEL_ORDERING_PROPERTY], [LEVEL_DBTYPE],
                   [LEVEL_MASTER_UNIQUE_NAME], [LEVEL_UNIQUE_NAME_SQL_COLUMN_NAME], [LEVEL_ATTRIBUTE_HIERARCHY_NAME],
                   [LEVEL_KEY_CARDINALITY], [LEVEL_ORIGIN], [DATASET_NAME], [LEVEL_NAME_SQL_COLUMN_NAME],
                   [LEVEL_KEY_SQL_COLUMN_NAME], [LEVEL_SORT_SQL_COLUMN_NAME], [LEVEL_DBTYPE_NAME_COLUMN],
                   [LEVEL_DBTYPE_SORT_COLUMN], [IS_PRIMARY], [PARENT_LEVEL_ID]
            FROM $system.MDSCHEMA_LEVELS
            WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]' AND [LEVEL_NAME] &lt;&gt; '(All)'
        """,
        "columns": [
            "CATALOG_NAME", "SCHEMA_NAME", "CUBE_NAME", "CUBE_GUID", "DIMENSION_UNIQUE_NAME",
            "HIERARCHY_UNIQUE_NAME", "LEVEL_NAME", "LEVEL_UNIQUE_NAME", "LEVEL_GUID", "LEVEL_CAPTION",
            "LEVEL_NUMBER", "LEVEL_CARDINALITY", "LEVEL_TYPE", "DESCRIPTION", "CUSTOM_ROLLUP_SETTINGS",
            "LEVEL_UNIQUE_SETTINGS", "LEVEL_IS_VISIBLE", "LEVEL_ORDERING_PROPERTY", "LEVEL_DBTYPE",
            "LEVEL_MASTER_UNIQUE_NAME", "LEVEL_UNIQUE_NAME_SQL_COLUMN_NAME", "LEVEL_ATTRIBUTE_HIERARCHY_NAME",
            "LEVEL_KEY_CARDINALITY", "LEVEL_ORIGIN", "DATASET_NAME", "LEVEL_NAME_SQL_COLUMN_NAME",
            "LEVEL_KEY_SQL_COLUMN_NAME", "LEVEL_SORT_SQL_COLUMN_NAME", "LEVEL_DBTYPE_NAME_COLUMN",
            "LEVEL_DBTYPE_SORT_COLUMN", "IS_PRIMARY", "PARENT_LEVEL_ID"
        ],
    },
    "measures_detail_df": {
        "sql": """
            SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [MEASURE_NAME], [MEASURE_UNIQUE_NAME],
                   [MEASURE_GUID], [MEASURE_CAPTION], [MEASURE_AGGREGATOR], [DATA_TYPE], [COLUMN_NAME],
                   [COLUMN_DATA_TYPE], [NUMERIC_PRECISION], [NUMERIC_SCALE], [MEASURE_UNITS], [DESCRIPTION],
                   [EXPRESSION], [MEASURE_IS_VISIBLE], [MEASURE_NAME_SQL_COLUMN_NAME], [MEASURE_UNQUALIFIED_CAPTION],
                   [MEASUREGROUP_NAME], [MEASURE_DISPLAY_FOLDER], [DEFAULT_FORMAT_STRING], [DATASET_NAME],
                   [IS_METRICAL_ATTRIBUTE], [PARENT_LEVEL_ID], [PARENT_LEVEL_NAME]
            FROM $system.MDSCHEMA_MEASURES
        """,
        "columns": [
            "CATALOG_NAME", "SCHEMA_NAME", "CUBE_NAME", "CUBE_GUID", "MEASURE_NAME", "MEASURE_UNIQUE_NAME",
            "MEASURE_GUID", "MEASURE_CAPTION", "MEASURE_AGGREGATOR", "DATA_TYPE", "COLUMN_NAME",
            "COLUMN_DATA_TYPE", "NUMERIC_PRECISION", "NUMERIC_SCALE", "MEASURE_UNITS", "DESCRIPTION",
            "EXPRESSION", "MEASURE_IS_VISIBLE", "MEASURE_NAME_SQL_COLUMN_NAME", "MEASURE_UNQUALIFIED_CAPTION",
            "MEASUREGROUP_NAME", "MEASURE_DISPLAY_FOLDER", "DEFAULT_FORMAT_STRING", "DATASET_NAME",
            "IS_METRICAL_ATTRIBUTE", "PARENT_LEVEL_ID", "PARENT_LEVEL_NAME"
        ],
    },
    "connection_groups_df": {
        "sql": """
            SELECT [ID], [NAME], [PLATFORM_TYPE], [ORGANIZATION_ID], [CONNECTION_ID], [FILESYSTEM_URI],
                   [FILESYSTEM_TYPE], [AGGREGATE_SCHEMA], [DATABASE], [IS_IMPERSONATION_ENABLED],
                   [IS_CANARY_ALWAYS_ENABLED], [IS_PARTIAL_AGG_HIT_ENABLED], [READ_ONLY]
            FROM $system.DBSCHEMA_CONNECTION_GROUPS
        """,
        "columns": [
            "ID", "NAME", "PLATFORM_TYPE", "ORGANIZATION_ID", "CONNECTION_ID", "FILESYSTEM_URI",
            "FILESYSTEM_TYPE", "AGGREGATE_SCHEMA", "DATABASE", "IS_IMPERSONATION_ENABLED",
            "IS_CANARY_ALWAYS_ENABLED", "IS_PARTIAL_AGG_HIT_ENABLED", "READ_ONLY"
        ],
    },
    "connection_subgroups_df": {
        "sql": """
            SELECT [GROUP_ID], [ID], [NAME], [HOSTS], [PORT], [CONNECTOR_TYPE], [USERNAME],
                   [IS_KERBEROS_CLIENT_ENABLED], [EXTRA_JDBC_FLAGS], [MANAGEMENT_CONSOLE_URL],
                   [DATABASE], [QUERY_ROLES]
            FROM $system.DBSCHEMA_CONNECTION_SUBGROUPS
        """,
        "columns": [
            "GROUP_ID", "ID", "NAME", "HOSTS", "PORT", "CONNECTOR_TYPE", "USERNAME",
            "IS_KERBEROS_CLIENT_ENABLED", "EXTRA_JDBC_FLAGS", "MANAGEMENT_CONSOLE_URL",
            "DATABASE", "QUERY_ROLES"
        ],
    },
    "dependency_df": {
        "sql": """
            SELECT [DATABASE_NAME], [OBJECT_TYPE], [TABLE], [OBJECT], [EXPRESSION], [REFERENCED_OBJECT_TYPE],
                   [REFERENCED_TABLE], [REFERENCED_OBJECT], [REFERENCED_EXPRESSION], [CATALOG_NAME], [CUBE_NAME]
            FROM $system.DISCOVER_CALC_DEPENDENCY
        """,
        "columns": [
            "DATABASE_NAME", "OBJECT_TYPE", "TABLE", "OBJECT", "EXPRESSION", "REFERENCED_OBJECT_TYPE",
            "REFERENCED_TABLE", "REFERENCED_OBJECT", "REFERENCED_EXPRESSION", "CATALOG_NAME", "CUBE_NAME"
        ],
    },
}

def build_query_xml(name: str, catalog: str) -> str:
    """Convenience: build the SOAP-wrapped XMLA for a registered query by name."""
    meta = CATALOG_QUERIES.get(name)
    if not meta:
        raise KeyError(f"Unknown catalog query: {name}")
    return build_xmla_query(meta["sql"], catalog, cube)
